<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>
<%@ include file="/WEB-INF/jsp/page/taglib.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Import Result</title>
<style type="text/css">
@import url("<%=basePath%>css/mobile_main.css");
</style>
<script type="text/javascript"> 
</script>
</head>
<body>
<form action="importPerformanceResultByExcel.action" enctype="multipart/form-data"	method="post" id="fileform">
<table class="form_table" id="form_table">
	<tr>
		<th colspan="2" class="form_head">Import Test Case</th>
	</tr>
	<tr id="tr_temp">
		<td>Choose Import Excel File:</td>
		<td>
			<input	type="file" name="upload" id="fileArea"></input> &nbsp;
		</td>
	</tr>
</table>

<table class="form_table">
	<tr>
		<td style="border-right:none;">
		</td>
		<td>
			<input name="subExecutionId" id="subExecutionId" value="<%= request.getParameter("subExecutionId") %>" style="display:none"/>
			<input type="submit" value="submit" class="btn1"></input>
		</td>
	</tr>
</table>
</form>
<h3 style="color:blue;">${successMsg }</h3>
<h3 style="color:red;">${errorMsg }</h3>
<!--
<fieldset>
 <legend>Feature Usage</legend>
<p>This feature is developed for bulk edit execution result in sub execution by XML, XML file is auto generated by automation framework.
</p>
</fieldset>
-->
</body>
</html>